### ISSUE TITLE
IEV improvements: provide indication of an "absent designation"

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/concept-model#10]
In the IEV `.....` the string of 5 periods indicate that a term is explicitly "absent".

We should add the designation type "absent" to allow differentiate between:
* a concept without designations
* a concept with an explicitly absent designation

e.g. [IEV 731-01-27](http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=731-01-27) de and fr.

**Comment by opoudjis** [comment]
Add +absent boolean attribute to designation.

**Comment by ronaldtse** [comment]
Closed in b10cf99
