### ISSUE TITLE
Use `lutaml` gem to generate the diagrams in this repo

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/concept-model#15]
The `datamodel` directory contains all models and views. Ping @w00lf

**Comment by ronaldtse** [comment]
@w00lf Are we ready to convert the diagram into new LutaML syntax?

**Comment by ronaldtse** [comment]
@w00lf looks like we're almost there? 👍

**Comment by w00lf** [comment]
> @w00lf looks like we're almost there? 👍

Conversion of datamodel files completed, old yaml files cleaned up, @ronaldtse feel free to close this issue if everything is ok now.

**Comment by ronaldtse** [comment]
Thanks @w00lf !
