### ISSUE TITLE
IEV improvements: Differentiate forms of "abbreviation" designations

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/concept-model#9]
> ISO 704:2009: abbreviations are created by omitting words and/or parts of a word making up a term. 
> Initialisms and acronyms are different forms of abbreviation. Also, all 3 are different types of "abbreviatedForm", as opposed to "fullForm", as specified in ISO 10241-1:2011, 3.4.1.2.4.

There are three types of abbreviations:
* omitting words and/or parts of a word making up a term. 
* initialisms
* acronyms

These should be differentiated in the model.

**Comment by opoudjis** [comment]
Changed model to:

AbbreviationDesignation is the only subclass there is; moved isInternational from AcronymDesignation to AbbreviationDesignation.

AbbreviationDesignation has abbreviationType: Acronym, Initialism, Truncation.
